### ISSUE TITLE
When blinking multiple times in a row light gets stuck

### ISSUE THREAD

**Issue by SnippetSpace** [chadwpalm/Lumunarr#18] opened 2023-08-08 10:35 UTC
I set 1 light to blink purple when a file gets added, when multiple get added at the same time sometimes the light not only stays on, but also stays purple. Might be worth checking for state a few seconds after the last trigger

**Comment by chadwpalm** [comment] 2023-08-09 00:03
It's probably running the blink command asynchronously on top of itself. I knew the first iteration of the Server notifications was a bit clunky and I never really ran them through extensive testing. I mostly added them as a novelty, but it seems a lot of people have been using them, so I should probably tighten up the code.

I already have 3 Hue related changes in the upcoming pipeline:

1.  To completely get rid of the use of the Huejay library on the backend, primarily because it's not being developed anymore and if it ever left the npm repo then it wouldn't be included in HuePlex builds anymore thus breaking things. I want all of my Hue API calls to be native and not rely on a library. I've got about 80% of its use cleaned out already, but as it so happens, what is left is the code for the Server tab (blinking included).

2. Hue will be deprecating v1 of the Hue API (they don't have a date set on that yet), so I need to update to v2 at some point to keep it from breaking when the time comes.

3. In conjunction with updating to v2, I also want to add functionality to connect to your Hue account which will allow remote access to bridges so that HuePlex and the bridge don't have to be on the same network.

I can take a look at making the blink stuff better when I'm working on #1. Hopefully sometime in the near future.

**Comment by SnippetSpace** [comment] 2023-08-09 08:05
Hey, thanks for the in depth explanation of upcoming challenges. With the partial rewrite and API version change the behavior is sure to change. Let’s see how it works post updates :)

**Comment by chadwpalm** [comment] 2023-10-14 21:23
Just pushed version 1.2.5.69 into the development branch that addresses this issue. If possible, please pull and test this branch to see if the problem is resolved.

**Comment by chadwpalm** [comment] 2024-06-25 05:05
Going to close this issue since the issue was addressed and nobody else has commented. If someone else has this problem they can reopen a new issue for it.

**Closed by chadwpalm** 2024-06-25 05:05 UTC
